all:
	pdflatex vas
bib:
	bibtex vas
full:
	pdflatex vas
	bibtex vas
	pdflatex vas
	pdflatex vas
clean:
	(rm -rf *.ps *.log *.dvi *.aux *.*% *.lof *.lop *.lot *.toc *.idx *.ilg *.ind *.bbl *.blg *.out *~)
